# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 307561a7b25b011c562b45d52afc2decd7d37981892b520fe0a135a7f52a9d86f03093474dadbc02dba38cb354f7dc1202c42c0da13284dc01c5935c2f4cc55b

test:
  secret_key_base: 06f3ecbb5d565e099d61cde583b10dd12647d48bd36fa940e2d89effb2816f860149c4b89e2c283528968a996dff9d4a9cc56eb885a484b2a88fa3a546d1b028

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
